apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: slack-notification-
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: do-something
        template: do-something
    - - name: notify-success
        template: slack-notify
        arguments:
          parameters:
          - name: status
            value: "Success"
        when: "{{steps.do-something.exitCode}} == 0"
      - name: notify-failure
        template: slack-notify
        arguments:
          parameters:
          - name: status
            value: "Failure"
        when: "{{steps.do-something.exitCode}} != 0"
  - name: do-something
    script:
      image: debian:9
      command: [bash]
      source: |
        # Do something here
  - name: slack-notify
    inputs:
      parameters:
      - name: status
    script:
      image: curlimages/curl:7.72.0
      command: [bash]
      source: |
        curl -X POST -H 'Authorization: Bearer $(cat /etc/slack/token)' -H 'Content-type: application/json' \
        --data '{"channel":"david-argo-notis","text":"Workflow {{workflow.name}} ended with status: {{inputs.parameters.status}}"}' \
        https://slack.com/api/chat.postMessage
    volumeMounts:
    - name: slack
      mountPath: /etc/slack
  volumes:
  - name: slack
    secret:
      secretName: slack-token