apiVersion: v1
kind: ServiceAccount
metadata:
  name: awf-workflow-controller-sa
  # namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awf-workflow-controller-role
rules:
  - apiGroups:
      - argoproj.io
    verbs:
      - create
      - patch
    resources:
      - workflowtaskresults
  - apiGroups:
      - ""
    verbs:
      - get
      - watch
      - patch
    resources:
      - pods
  - apiGroups:
      - ""
    verbs:
      - create
    resources:
      - pods/exec
  - apiGroups:
      - ""
    verbs:
      - get
    resources:
      - pods/log
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: awf-workflow-controller-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: awf-workflow-controller-role
subjects:
  - kind: ServiceAccount
    name: awf-workflow-controller-sa
    namespace: argo
    # namespace: default
