apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: add-example-
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: addFour
            template: addFour
            arguments:
              parameters:
                - name: "a"
                  value: "2"
                - name: "b"
                  value: "5"
        - - name: sayHello
            template: sayHello
            when: "{{steps.addFour.outputs.result}} > 5"
    - name: addFour
      inputs:
        parameters:
          - name: "a"
          - name: "b"
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["echo $(( {{inputs.parameters.a}} + {{inputs.parameters.b}} ))"]
    - name: sayHello
      container:
        image: alpine:latest
        command: [sh, -c]
        args: [echo "Hello Intuit!"]