apiVersion: v1
kind: Service
metadata:
  namespace: argo-events
  name: webhook-eventsource
spec:
  ports:
  - port: 12000
    protocol: TCP
    targetPort: 12000
  selector:
    eventsource-name: http-create-eventsource
  type: LoadBalancer